### PR TITLE
add logging to ecs cluster provider

### PR DESCRIPTION
**Pull request by webern**
**Issue number:**

N/A

**Description of changes:**

It's pretty frustrating when you're having trouble with a program and it doesn't output any logs at all.

**Testing done:**

I used it and saw the logs.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by webern** [comment]
^ clippy

**Comment by webern** [comment]
CI failing because of the problem that #388 will fix

**Comment by webern** [comment]
^ rebase - should fix image build problem

**Comment by webern** [comment]
^ rebase

**Review by etungsten — APPROVED** [review]

**Review by jpculp — APPROVED** [review]

**Pull request merged**
