### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by ecpullen**
**Issue number:**

N/A

**Description of changes:**

Updates packages to keep dependabot happy.

**Testing done:**

CI passed.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by etungsten — APPROVED** [review]

**Comment by arnaldo2792** [comment]
Was there a reason why this update is needed, or is this just a "chore" update?

**Comment by ecpullen** [comment]
> Was there a reason why this update is needed, or is this just a "chore" update?

Just maintenance.

**Review by jpculp — APPROVED** [review]
nit. It might be useful to have the commit saying something about updating `aws-rust-sdk` to 0.15 or something, just in case you have to roll back.

**Review by zmrow — APPROVED** [review]
:hamburger:

**Comment by ecpullen** [comment]
^ Dropped `unicode-ident` to 1.0.1 for licenses check.

**Pull request merged**
