### PR TITLE
actions: Update rustc to 1.78

### PR DESCRIPTION
**Pull request by sumukhballal**
**Issue number:**

**Description of changes:**

Updates actions rustc to v1.78 the same as the [SDK](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/v0.42.0/hashes/rust). 

**Testing done:**

- Actions should pass.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by sumukhballal** [comment]
Pushed some clippy fixes.

**Review by gthao313 — APPROVED** [review]

**Comment by gthao313** [comment]
Tests haven been passed.
```
 NAME                                                                                   TYPE                                  STATE                                                             PASSED                              FAILED                              SKIPPED
 x86-64-aws-ecs-1-migration-test-cluster-test-1-initial                                 Test                                  passed                                                                 1                                   0                                    0
 x86-64-aws-ecs-1-migration-test-cluster-test-2-migrate                                 Test                                  passed                                                                 2                                   0                                    0
 x86-64-aws-ecs-1-migration-test-cluster-test-3-migrated                                Test                                  passed                                                                 1                                   0                                    0
 x86-64-aws-ecs-1-migration-test-cluster-test-4-migrate                                 Test                                  passed                                                                 2                                   0                                    0
 x86-64-aws-ecs-1-migration-test-cluster-test-5-final                                   Test                                  passed                                                                 1                                   0                                    0
 x86-64-aws-ecs-1-test-cluster-test                                                     Test                                  passed                                                                 1                                   0                                    0
 x86-64-aws-k8s-124-migration-test-cluster-test-1-initial                               Test                                  passed                                                                 1                                   0                                 6972
 x86-64-aws-k8s-124-migration-test-cluster-test-2-migrate                               Test                                  passed                                                                 2                                   0                                    0
 x86-64-aws-k8s-124-migration-test-cluster-test-3-migrated                              Test                                  passed                                                                 1                                   0                                 6972
 x86-64-aws-k8s-124-migration-test-cluster-test-4-migrate                               Test                                  passed                                                                 2                                   0                                    0
 x86-64-aws-k8s-124-migration-test-cluster-test-5-final                                 Test                                  passed                                                                 1                                   0                                 6972
 x86-64-aws-k8s-124-test-cluster-test                                                   Test                                  passed                                                                 1                                   0                                 6972
 x86-64-aws-ecs-1-migration-test-cluster                                                Resource                              completed
 x86-64-aws-ecs-1-migration-test-cluster-instances                                      Resource                              completed
 x86-64-aws-ecs-1-test-cluster                                                          Resource                              completed
 x86-64-aws-ecs-1-test-cluster-instances                                                Resource                              completed
 x86-64-aws-k8s-124-migration-test-cluster                                              Resource                              completed
 x86-64-aws-k8s-124-migration-test-cluster-instances                                    Resource                              completed
 x86-64-aws-k8s-124-test-cluster                                                        Resource                              completed
 x86-64-aws-k8s-124-test-cluster-instances                                              Resource                              completed
```

**Review by jpculp — CHANGES_REQUESTED** [review]
Let's drop the kube commit for now. We should bump the AWS SDK for Rust first.

**Comment by cbgbt** [comment]
No longer needed after #919

**Pull request closed without merging**
