### PR TITLE
Remove `bottlerocket/testsys` cli

### LINKED ISSUE #438: cli: remove bottlerocket/testsys
When we are no longer using the "legacy" CLI, remove it.

### PR DESCRIPTION
**Pull request by ecpullen**
**Issue number:**

Closes #438 

**Description of changes:**

Removes the legacy cli from the project.

**Testing done:**

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by webern — APPROVED** [review]
Big :tada:  

Edit: there's a thing or two to delete in the github actions configuration.

**Review by stmcginnis — CHANGES_REQUESTED** [review]
Documentation needs to be updated to reflect this change. Most of the docs in this repo refer to using `cli` to do things. Before we take that away, we should have the new recommendations for what to do instead.

**Comment by ecpullen** [comment]
> Documentation needs to be updated to reflect this change. Most of the docs in this repo refer to using `cli` to do things. Before we take that away, we should have the new recommendations for what to do instead.

`cli` is not being removed. The old `testsys` cli that hasn't been used is the one being removed. Following this pr it may be better to rename `cli` `testsys-cli.

Edit: I see the Quickstart guide uses the old cli. 😞

**Comment by mjsterckx** [comment]
There are references to the `testsys` directory/CLI in `README.md`, `DESIGN.md`, and `DEVELOPER.md` but I'm not sure if removing those is the responsibility of https://github.com/bottlerocket-os/bottlerocket-test-system/pull/757 or this PR (since 757 will be merged first and the `testsys` directory will not be removed yet at that point).

**Comment by ecpullen** [comment]
I will cover Design, readme and developer.

**Review by etungsten — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
